# Generated by Django 5.1.7 on 2025-04-06 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("cash", "Наличные"), ("transfer", "Перевод на счет")],
                default="transfer",
                max_length=30,
                verbose_name="метод оплаты",
            ),
        ),
    ]
