# Generated by Django 5.1.7 on 2025-04-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Наличные", "Наличные"),
                    ("Перевод на счет", "Перевод на счет"),
                ],
                default="Перевод на счет",
                max_length=30,
                verbose_name="метод оплаты",
            ),
        ),
    ]
