# Generated by Django 5.2 on 2025-04-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличные", "Наличные"), ("Перевод на счет", "pm_card_visa")],
                default="Перевод на счет",
                max_length=30,
                verbose_name="метод оплаты",
            ),
        ),
    ]
