# Generated by Django 5.2 on 2025-04-09 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_payment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("Наличные", "Наличные"), ("pm_card_visa", "Перевод на счет")],
                default="pm_card_visa",
                max_length=30,
                verbose_name="метод оплаты",
            ),
        ),
    ]
