services:
  web:
    build:
      dockerfile: Dockerfile
#    command: poetry run python manage.py collectstatic --noinput && gunicorn config.wsgi:application --bind 0.0.0.0:8000
    command: poetry run python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/drf_project
      - static_volume:/drf_project/staticfiles/
#    ports:
#      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    env_file:
      - ./.env

  nginx:
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/drf_project/staticfiles/
    depends_on:
      - web

  db:
    image: postgres
    env_file:
      - ./.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    expose:
      - "5432"
    healthcheck:
      test: [ 'CMD-SHELL', '-c', 'pg_isready -U skypro -d drf_learn' ]
      interval: 10s
      retries: 5
      timeout: 5s

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5

  celery:
    build: .
    command:
      poetry run celery -A config worker -l INFO --concurrency=500 --pool=gevent
    restart: on-failure
    volumes:
      - .:/drf_project
    depends_on:
      - redis
      - db
    env_file:
      - ./.env

  celery-beat:
    build: .
    command:
      poetry run python manage.py migrate django_celery_beat &&
      poetry run celery -A config beat --loglevel=info --scheduler django_celery_beat.schedulers:DatabaseScheduler
#      poetry run celery -A config beat --loglevel=info
#    restart: on-failure
    restart: unless-stopped
    volumes:
      - .:/drf_project
      - celerybeat_volume:/var/lib/celery
    depends_on:
      - redis
      - db
      - web
    env_file:
      - ./.env
    healthcheck:
      test: [ "CMD-SHELL", "celery -A config inspect ping -d celery@$$HOSTNAME | grep -q 'pong'" ]
      interval: 30s
      timeout: 10s
      retries: 3


volumes:
  pg_data:
  static_volume:
  redis_data:
