# Generated by Django 5.1.7 on 2025-04-01 05:52

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lms", "0003_coursesubscription"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="subscribers",
            field=models.ManyToManyField(
                blank=True,
                related_name="subscribed_courses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
